ecc_theme/ecc_theme.theme

remove unexpected * in ecc_theme.theme causing error in drupal

Bugfix: remove unexpected * from ecc_theme.theme

---

ecc_theme/css/ecc-shared/services.css

- removes width calc that was causing icon to be cut off 
- this also fixes ECCW-669

ECCI-536: removes width calc causing icon to cut off

---

ecc_theme/css/ecc-shared/media-with-text.css

- Fixes bg-color for --circle
- creates vertical stacking display (with media on top) for mobile for --right and --left media components
- fixes --right and --left featured component
To do: Clarify max-width of --circle top and bottom components prior to merging.

bugfix/ECCI-537-538: Adds styles for media-with-text

---

ecc_theme/css/ecc-shared/pagination.css

removes black bg on these links:

ECCI-543: removes black bg from next/prev links

---

ecc_theme/css/ecc-shared/headings.css

adds spacing for header and :after element

ECCI-541: adds spacing for header and :after

---

ecc_theme/css/ecc-shared/layout.css

Using devtools, I found disabling `width` around line 28 of this file, and the image no longer appears as an oval.
- There are no links.
- It was one of the few things that I know how to do.
- I'm not convinced that this _doesn't_ introduce regressions this stage.
---
*Before:*
---
*After:*
---

ECCI-538: Removal of width causes circle to render properly.

---

ecc_theme_gov/css/buttons.css
ecc_theme_gov/ecc_theme_gov.libraries.yml

While prepping the gov site to use 1.0.16, I spotted errors the `buttons.css` file was not present.
- I suspect that there may be some necessary styling for buttons, but don't know what the design requirements are, so duplicated the intranet site and am creating this PR as a draft until a decision is made.
- If not needed, the file will need removing, as does the reference to it in `ecc_theme_gov.libraries.yml`.
- None whatsoever in my limited skim though the site in my local build. As I saw no difference, when comparing to prod, perhaps it's not needed whatsoever?

ECCW-675: Missing buttons.css file for ecc_theme_gov theme.

---

ecc_theme/css/ecc-shared/layout.css

Currently:
Should be:
The README says not to add margins directly to components so I have added the style in layouts.css, next to the style that it is overriding.
Both websites have service-cta-block.css files, containing different styles. I don't know if this is correct or if they should be the same. To minimise the risk of introducing new issues, I've only fixed the bug that has been raised, but this may have to be addressed later.

ECCI-549: Restore margin-bottom for top task buttons.

---

ecc_theme/css/ecc-shared/variables-shared.css
ecc_theme_gov/css/variables-gov.css

Start button should be green for both websites so the variables should be in the shared theme. (Currently missing from Intranet)

ECCI-544: Move start button colours to shared theme.

---

ecc_theme/css/ecc-shared/layout.css

On service landing pages, the link text in of second rows onwards appear to have an indent. 
Screenshot Pre-prod Intranet

ECCI-541: Formatting issue on service landing pages

---

ecc_theme/css/ecc-shared/variables-shared.css

The variable font-size for the body has been changed to use the same as the live site.

ECCI-549 Changed body font-size to be consistent with live site

---

ecc_theme/css/ecc-shared/layout.css
ecc_theme_intranet/css/hero.css
ecc_theme_intranet/css/search.css

Fixed quick links position on mobile and added space of 1rem

ECCI-563 fixed quick links position on mobile

---

ecc_theme_gov/ecc_theme_gov.theme
ecc_theme_intranet/ecc_theme_intranet.theme

The last breadcrumb is duplicated because of identical functions in ecc_theme and ecc_theme_gov for hook_preprocess_breadcrumb.
Remove two hooks from ecc_theme_gov and ecc_theme_intranet which are also present in ecc_theme

LP-87: Remove duplicate functions from themes.

---

ecc_theme/templates/content/node--localgov-event--full.html.twig

Fixes this error which refers to the old _essex_ theme
`php.ERROR: Twig\Error\LoaderError: Template "@essex/templates/_components/add-to-calendar.twig" is not defined in "themes/contrib/ecc_theme/ecc_theme/templates/content/node--localgov-event--full.html.twig" at line 136. in Twig\Loader\ChainLoader->getCacheKey() (line 99 of /drupal/vendor/twig/twig/src/Loader/ChainLoader.php).`

LP-26: Update theme name for add-to-calendar.twig

---

ecc_theme/css/ecc-shared/event-teaser.css
ecc_theme/css/ecc-shared/events.css
ecc_theme/ecc_theme.libraries.yml
ecc_theme/templates/content/node--localgov-event--teaser.html.twig

Fixes: https://eccservicetransformation.atlassian.net/browse/LP-96
- Adds teaser template for events in teaser view mode (I'd prefer if we had a global node--teaser.html.twig for this)
- Add CSS for teaser events (I'd prefer if we had global .teaser CSS for this)
- Adds a library for events teaser (let's create a follow up to have all content types using the same CSS)

adds theming for events in teaser view mode

---

ecc_theme/css/ecc-shared/events.css

At the moment if an event has an image and a call to action, the CTA is bucking up against the image. This adds generic spacing to all items in the event content div.
Fixes: https://eccservicetransformation.atlassian.net/jira/software/projects/LP/boards/25?assignee=557058%3A8b7fbfd8-fba0-4c51-bd41-0b1d0e7d6ebe&selectedIssue=LP-26

adds spacing between items for events in full view mode

---

ecc_theme_gov/css/subsites-menu.css

fix(FOS-85): Set background to white on active item in subsite menu.

---

ecc_theme/css/ecc-shared/layout.css

The spacing between paragraphs is too large when a "Read more" link is associated with a pull quote above it. 
The best solution would be to add a new link field to the quote paragraph but this is out of scope for now. A compromise is to reduce the margin above a text paragraph when it immediately follows a quote.
The spacing was adjusted earlier but was still too large
https://github.com/essexcountycouncil/ecc_theme/commit/0a81f7ea203ab35f3429f49d82616326cca0e59b

fix(FOS-79): Reduce spacing between quote and text paragraph.

---

ecc_theme_gov/css/subsites.css

The purple background and white line make it obvious that the margin above the search bar is too big. 
This change only affects subsites in case of unexpected consequences on the rest of the website.

fix(FOS-86): Reduce top margin for subsites search bar

---

ecc_theme/css/ecc-shared/accordion.css

Avoids clash between text and accordion chevron at high levels of desktop browser zoom.
Ticket: https://eccservicetransformation.atlassian.net/jira/software/projects/LP/boards/25?selectedIssue=LP-125

Add right padding to accordion button to avoid clash at high zoom.

---

ecc_theme_gov/ecc_theme_gov.theme

- Removes the second item if it's the "Chidren, young people and families" breadcrumb

FOS-97: Manipulate the breadcrumbs for fostering.

---

ecc_theme_intranet/css/search.css
ecc_theme_intranet/templates/layout/header.html.twig
ecc_theme_intranet/templates/layout/page.html.twig

https://eccservicetransformation.atlassian.net/jira/software/projects/LP/boards/25?selectedIssue=LP-126
Changes source order to match expected tab order and visual order in header elements for Intranet.
Includes:
- removal of tab order index in search.css
- addition of custom header.html.twig to swap source order for search element and menu element
- change to page template to use new custom header template.
1. Load a non-homepage page. e.g. `/employee-support`
2. Tab through the first few page elements using the `tab` key, noting each highlighted element.
3. Note that progress is: skip > logo > search > search input > search button > menu
Compare to behaviour on production, where menu occurs before search in the tab order.

202408 tab order lp 126

---

ecc_theme_gov/templates/layout/page.html.twig
ecc_theme_intranet/templates/layout/page.html.twig

A better, simpler solution for the Skip Link Problem. https://eccservicetransformation.atlassian.net/browse/LP-127
adds tabindex -1 to MAIN element, allowing focus.
Adds it in page.html.twig for both themes.

Add tabindex -1 to main element for both gov and intranet

---

ecc_theme_intranet/css/variables-intranet.css

makes the base line height the same as .gov theme.
1.5 units as opposed to 1.3.
https://eccservicetransformation.atlassian.net/browse/LP-176

Make intranet line height base match .gov line height value

---

ecc_theme/templates/content/node--localgov-guides-overview--full.html.twig
ecc_theme_gov/templates/content/node--localgov-guides-overview--full.html.twig

https://eccservicetransformation.atlassian.net/browse/LP-138
Changes guide overview full node templates.
1 line change in each, changed to match localgov base implementation.
Print the field value if there, otherwise print default value.

Print guide overview title, not just the default value of 'overview'.

---

ecc_theme_gov/config/schema/ecc_theme_gov.schema.yml
ecc_theme_intranet/config/schema/ecc_theme_intranet.schema.yml

it looks like child themes need their own config schema, even for settings defined in the base theme. This means that ECC Theme Gov and Intranet don’t know that the draft setting is supposed to be boolean.
Copied schema from localgov_base and change setting name in the first line.

fix(LP-48):  Add schema to themes to ensure draft flag is boolean.

---

ecc_theme/templates/paragraphs/paragraph--localgov-call-out-box.html.twig

Only print the callout link button if there is an actual link to print.
Resolves the problem of printing an empty button, meaning you always need to include a link.
part of https://eccservicetransformation.atlassian.net/browse/LP-175

Only print the button for call out box link if there's a URL present.

---

ecc_theme/templates/field/field--field-directory-page-access.html.twig
ecc_theme/templates/field/field--field-directory-page-age.html.twig
ecc_theme/templates/field/field--field-directory-page-location.html.twig
ecc_theme/templates/field/field--node--body--localgov-directories-page.html.twig
ecc_theme/templates/field/field--node--localgov-directory-email--localgov-directories-page.html.twig
ecc_theme/templates/field/field--node--localgov-directory-phone--localgov-directories-page.html.twig
ecc_theme/templates/field/field--node--localgov-directory-website--localgov-directories-page.html.twig

Adds the following field templates:
1. field--field-directory-page-access.html.twig
2. field--field-directory-page-age.html.twig
3. field--field-directory-page-location.html.twig
4. field--node--body--localgov-directories-page.html.twig
5. field--node--localgov-directory-email--localgov-directories-page.html.twig
6. field--node--localgov-directory-phone--localgov-directories-page.html.twig
7. field--node--localgov-directory-website--localgov-directories-page.html.twig
so that we can output labels with appropriate heading markup
https://eccservicetransformation.atlassian.net/browse/LP-308

Add field templates to adjust label markup for directory page fields

---

ecc_theme/css/ecc-shared/blockquote.css

remedy a regression where quote icon gets partially obscured by insufficient padding.

Restore lost padding between quote icon and the quote itself.

---

ecc_theme_gov/ecc_theme_gov.libraries.yml

Fixes CSS paths in ecc_theme_gov libraries file for the new subsites folders.

Point gov theme libraries at the correct path for subsite css

---

ecc_theme/css/ecc-shared/blockquote.css

block quote icon is made with a mask.
It was repeating.
This makes it stop.
https://eccservicetransformation.atlassian.net/browse/LP-282

Do not let blockquote icon repeat

---

ecc_theme/css/ecc-shared/headings.css

Prevents directory page h2s from getting a red underline style.
Extends the existing paradigm of exclusions.
https://eccservicetransformation.atlassian.net/browse/LP-308

Prevent directory page h2s from getting the red underline style

---

ecc_theme/css/ecc-shared/page-sections.css

we have a situation where a section can have a pink background, but links remain white.
This changes links to use Essex blue, using the existing defined link colour variable.

Make links essex blue on pink tint sections.

---

ecc_theme/css/ecc-shared/page-sections.css

in https://eccservicetransformation.atlassian.net/browse/LP-285
we made links blue on the pink tint background.
Now we're doing the same for lilac tint and light grey.
https://eccservicetransformation.atlassian.net/browse/LP-354

Ensure blue links on lilac and grey section backgrounds

---

ecc_theme_gov/ecc_theme_gov.theme

on this page https://www.essex.gov.uk/children-young-people-and-families 
the breadcrumb is shortened.
This is fine on all other relevant pages, e.g. https://www.essex.gov.uk/children-young-people-and-families/report-concern-about-child
but not here. We want the title of the page to be shown in the breadcrumb here.
https://eccservicetransformation.atlassian.net/browse/LP-341

Do not hide CYPAF breadcrumb on its own page.

---

ecc_theme_gov/ecc_theme_gov.theme

we want the whole breadcrumb on non fostering pages, so only apply the breadcrumb modification to fostering pages.
https://eccservicetransformation.atlassian.net/browse/LP-341

Only hide children etc breadcrumb element on fostering pages

---

ecc_theme_gov/config/schema/ecc_theme_gov.schema.yml
ecc_theme_intranet/config/schema/ecc_theme_intranet.schema.yml

v 1.8.11 of localgov_base introduces a theme setting for marking nodes as archived (like the existing draft setting)
this change adds that variable into our schemas, just like was done for the draft setting last year.
https://eccservicetransformation.atlassian.net/jira/software/projects/LP/boards/25?selectedIssue=LP-278

Add archived boolean definitions to theme schemas to match new lgd base theme

---

ecc_theme_gov/css/subsites/digitalessex/digitalessex.css

for digital essex subsite theme the logo is a link, but it was inheriting inappropriate hover and focus states.
This makes them a nice dashed white border.
https://eccservicetransformation.atlassian.net/browse/LP-366

Apply hover and focus states to link for digital essex logo
