essexcountycouncil/ecc_theme

ecc_theme/css/ecc-shared/layout.css

removed 100% layout height on 2-column layouts

[bugfix/2-col-layout-height] removed 100% layout height

---

ecc_theme/css/ecc-shared/media-with-text.css

example component: 
media with text, style = circle

ECCI-538: adds changes for media-with-text--circle

---

ecc_theme/.gitignore
ecc_theme/assets/images/ecc-shared/arcs/arc-down.svg
ecc_theme/assets/images/ecc-shared/arcs/arc-up.svg
ecc_theme/css/ecc-shared/edit-tabs.css
ecc_theme/css/ecc-shared/featured-teasers.css
ecc_theme/css/ecc-shared/headings.css
ecc_theme/css/ecc-shared/layout.css
ecc_theme/css/ecc-shared/page-sections.css
ecc_theme/css/ecc-shared/variables-shared.css
ecc_theme/ecc_theme.info.yml
ecc_theme/ecc_theme.libraries.yml
ecc_theme/ecc_theme.theme
ecc_theme/layouts/threecol_33_34_33/threecol_33_34_33.css
ecc_theme_intranet/css/layout.css
ecc_theme_intranet/css/search.css

adds css and register new libraries for marks components

adds css for Release/mark-202301-01 to main #367

---

ecc_theme_intranet/css/search.css

reduce padding on search bar component to align search and icon.

ECCI-535: adjust padding on search bar component

---

ecc_theme/css/ecc-shared/layout.css
ecc_theme/css/ecc-shared/media-with-text.css

Adds styles for --featured style media-with-text component:

ECCI-537: adds styles for --featured style on media-with-text component

---

ecc_theme/css/ecc-shared/ia-block.css
ecc_theme/ecc_theme.info.yml
ecc_theme/ecc_theme.libraries.yml
ecc_theme/ecc_theme.theme

- adds ia-block.css file
- added ia-block library
- references ia-block in info.yml
To-do: check requirements for background of this component

ECCW-667: adds styles to specifically to ia-block. adds ia-block.css

---

ecc_theme/css/ecc-shared/media-with-text.css
ecc_theme/css/ecc-shared/variables-shared.css
ecc_theme/ecc_theme.info.yml
ecc_theme/ecc_theme.libraries.yml

- Adds curve.css 
- Added curve to libraries.yml
- References curve in info.yml
- This also fixes media-with-text--circle, which was appearing as an oval due to max-height being set

ECCI-533: adds curve.css also fixes media-with-text--circle

---

ecc_theme/css/ecc-shared/curve.css
ecc_theme/css/ecc-shared/page-sections.css

missing curve.css file now added!

ECCI-533-curve: adds missing curve.css file

---

ecc_theme/css/ecc-shared/page-sections.css

Adds changes from styles mark added: bg-colors

bugfix-374: adds styles from mark changes bg-color media-text

---

ecc_theme_gov/templates/layout/status-pages/page--403.html.twig
ecc_theme_gov/templates/layout/status-pages/page--404.html.twig

LP-58: Essex Gov 404 error incorrect page displayed.

---

ecc_theme/css/ecc-shared/guide.css

ECCI-542: reduces bullet size for aligning guide bullets

---

.github/PULL_REQUEST_TEMPLATE.md

To line up with the other repos, let's have a template, shall we?

ECCW-0: Added the PR template.

---

CONTRIBUTING.md
README.md

CONTRIBUTIONS.md

---

ecc_theme/css/ecc-shared/ckeditor.css
ecc_theme/ecc_theme.info.yml

LP-40 is to fix inset and start button styling using CKEditor. This PR will be used alongside config changes so that CKEditor behaves the same on Gov and Intranet. 
The CKEditor styles have been mostly copied from Gov custom theme.

LP-40: Add CKEditor styles, mostly copied from Gov custom theme.

---

ecc_theme/css/ecc-shared/buttons.css
ecc_theme/ecc_theme.info.yml
ecc_theme/ecc_theme.libraries.yml
ecc_theme_intranet/css/buttons.css
ecc_theme_intranet/ecc_theme_intranet.info.yml
ecc_theme_intranet/ecc_theme_intranet.libraries.yml

I _think_ all button styles should be the same on Gov and Intranet so the styles should all be in the base theme.

ECCI-544: Move button styles into shared theme.

---

ecc_theme/css/ecc-shared/layout.css

ECCI-539: Add missing layout CSS for featured teaser and news card.

---

ecc_theme/css/ecc-shared/headings.css
ecc_theme/css/ecc-shared/layout.css

ECCI-548 Fixed the spacing issue between heading and text

---

ecc_theme/css/ecc-shared/headings.css

ECCI-541 fixed margin and font-size

---

ecc_theme/css/ecc-shared/curve.css
ecc_theme/css/ecc-shared/date-time.css
ecc_theme/css/ecc-shared/hero.css
ecc_theme/css/ecc-shared/layout.css
ecc_theme/css/ecc-shared/news.css

ECCI-525 Ensure News 1+4 component has the styles as live site

---

ecc_theme/css/ecc-shared/layout.css

ECCI-567 decrease the size of the cludo search loading icon

---

ecc_theme/css/ecc-shared/news.css

ECCI-568 fixed news listing layout

---

ecc_theme/css/ecc-shared/add-to-calendar.css
ecc_theme/css/ecc-shared/events-listing-page.css
ecc_theme/ecc_theme.libraries.yml
ecc_theme/ecc_theme.theme
ecc_theme/js/add-to-calendar.js
ecc_theme/templates/_components/add-to-calendar.twig
ecc_theme/templates/content/node--localgov-event--full.html.twig

Duplicates code from essex theme which hadn't been deployed: https://github.com/essexcountycouncil/essex-gov-uk-drupal/pull/381/files#diff-a044063ad0f54342ec8a82e99dc691ac9097095364dab380b3c1542f53cfcaad

adds events styling and add-to-calendar feature

---

ecc_theme/css/ecc-shared/page-sections.css

Code cherry-picked from undeployed code from old essex theme: https://github.com/essexcountycouncil/essex-gov-uk-drupal/pull/374

sets background colours for media with text in advanced layouts

---

ecc_theme/css/ecc-shared/grid.css
ecc_theme/ecc_theme.libraries.yml
ecc_theme/ecc_theme.theme

Adding a temp grid system for views, while waiting on https://github.com/localgovdrupal/localgov_base/pull/537 to get merged.
If https://github.com/localgovdrupal/localgov_base/pull/537 doesn't get merged, this will make a pretty solid grid system for ourselves, and everyone else will be jealous 😉

adds (temp) grid system for views

---

ecc_theme/css/ecc-shared/events-listing-page.css

Fixes https://eccservicetransformation.atlassian.net/jira/software/projects/LP/boards/25?label=ReleaseA&selectedIssue=LP-99

adds margin for events pager

---

ecc_theme/css/ecc-shared/events-listing-page.css
ecc_theme/css/ecc-shared/sidebar.css

Fixes: https://eccservicetransformation.atlassian.net/jira/software/projects/LP/boards/25?label=ReleaseA&selectedIssue=LP-98

Lp 98/events layout mobile

---

ecc_theme/css/ecc-shared/contact.css

https://eccservicetransformation.atlassian.net/browse/LP-218
Add space and colon after contact component office hours field labels

Add space and colon after contact component office hours field labels

---

ecc_theme/templates/paragraphs/paragraph--localgov-featured-teaser.html.twig

Adjusts featured teaser paragraph so that it wraps the link around the heading and hides the link text.
https://eccservicetransformation.atlassian.net/browse/LP-280

Make featured teaser link the heading and hide the link.

---

ecc_theme/templates/paragraphs/paragraph--localgov-featured-teaser.html.twig

fix(LP-301): Fix link in featured teaser.

---

ecc_theme/css/ecc-shared/page-sections.css
ecc_theme/templates/paragraphs/paragraph--localgov-page-section.html.twig

https://eccservicetransformation.atlassian.net/browse/LP-228
Refactor curves template and css so that they work like Love Essex. i.e. properly.

Adjust section curves to make them behave properly.

---

ecc_theme/css/ecc-shared/media-with-text.css

Restrict the max size of circular images for media-with-text

---

ecc_theme/css/ecc-shared/accordion.css

Allow accordions to inherit accent colour of site/subsite

---

ecc_theme/css/ecc-shared/accordion.css

colours for accordions within facet widgets
https://eccservicetransformation.atlassian.net/browse/LP-334

Make accordions in facets use link colour not accent colour

---

ecc_theme_gov/css/subsites/fostering/fostering.css

https://eccservicetransformation.atlassian.net/browse/LP-339

Make sure fostering accordion colours only apply to fostering pages

---

ecc_theme_intranet/css/disclosure-nav.css
ecc_theme_intranet/css/header.css
ecc_theme_intranet/css/main-menu.css
ecc_theme_intranet/templates/layout/status-pages/page--403.html.twig
ecc_theme_intranet/templates/layout/status-pages/page--404.html.twig
ecc_theme_intranet/templates/layout/status-pages/page-status.html.twig

ECCI-580: Bugfixes for EECI-581, 582, 583, 584, 585, 587, 588, 589

---

ecc_theme_intranet/css/disclosure-nav.css

fixes positioning of disclosure nav

ECCI-uat-fixes: fixes positioning of disclosure nav

---

ecc_theme_intranet/css/three-col-layout.css
ecc_theme_intranet/ecc_theme_intranet.info.yml
ecc_theme_intranet/ecc_theme_intranet.libraries.yml

ECCI-uat-bugfixes: Resolves issue with misaligned columns on mobile for three-column layout

---

ecc_theme_intranet/ecc_theme_intranet.theme

Add title attribute to link in CTA link paragraph

ECCI-580: Add optional title to CTA link.

---

ecc_theme_gov/css/subsites/digitalessex/digitalessex.css

Makes subsite logo for digital essex clickable.
https://eccservicetransformation.atlassian.net/browse/LP-366

202505 subsitelogolink lp 366
